[package]
name = "icfp2018"
version = "0.1.0"
authors = ["Hayato Ito <hayato@google.com>"]

[dependencies]
loggerv = "0.7.1"
structopt = "0.2.10"
failure = "0.1.1"
log = "0.4.3"
serde_derive = "1.0.70"
serde_json = "1.0.24"
serde = "1.0.70"
chrono = "0.4.4"
lazy_static = "1.0.2"
rayon = "1.0.2"
